# Generated by Django 2.2.4 on 2019-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPlotReg',
            fields=[
                ('plot_no', models.IntegerField(primary_key=True, serialize=False)),
                ('road_no', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('cost_per_sq_yard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expences', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boundaries', models.CharField(max_length=30)),
                ('facing', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
