# Generated by Django 2.2.4 on 2019-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newplotreg',
            name='plot_area_in_sq_yard',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
