# Generated by Django 2.2.4 on 2019-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_newplotreg_plot_area_in_sq_yard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newplotreg',
            name='plot_area_in_sq_yard',
            field=models.CharField(max_length=30),
        ),
    ]
