# Generated by Django 2.2.4 on 2019-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191027_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPARTmentCReg',
            fields=[
                ('app_no', models.IntegerField(primary_key=True, serialize=False)),
                ('app_floors', models.IntegerField()),
                ('app_status', models.CharField(max_length=30)),
                ('app_area', models.CharField(max_length=30)),
                ('app_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
