# Generated by Django 2.2.4 on 2019-10-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_appartmentcreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('plot_sales_rs', models.IntegerField()),
                ('appartment_sales_rs', models.IntegerField()),
                ('total_sales_rs', models.IntegerField()),
            ],
        ),
    ]
